version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 27017:27017
    volumes:
      - local-mongo:/data/db
    command: [--auth]

volumes:
  local-mongo:
    driver: local 
